server:
  port: 8081

spring:
  graphql:
    schema:
      locations: classpath*:graphql/**/
    graphiql:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/IgodatingKeycloak
      client:
        registration:
          keycloak:
            client-authentication-method: client_secret_basic
            client-id: igodating-questionary-service
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/IgodatingKeycloak
            user-name-attribute: preferred_username
  cloud:
    openfeign:
      client:
        config:
          textEmbeddingService.url: http://localhost:5000/api/v1/
  application:
    name: igowed-questionary-service
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 50
    url: jdbc:postgresql://localhost:5432/igodating
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        default_schema: questionary
        dialect: org.hibernate.dialect.PostgreSQLDialect

task:
  user-questionary-embedding-calculation-task:
    cron: 0 0/1 * * * ?
    batch-size: 100
    threads-count: 5
