/**
 * Chat service API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChatShared } from './chatShared';

export interface ActionResultChatShared { 
    value?: ChatShared;
    success?: boolean;
    service?: ActionResultChatShared.ServiceEnum;
    errorCode?: string;
    message?: string;
    errorValue?: any;
    targetUrl?: string;
}
export namespace ActionResultChatShared {
    export type ServiceEnum = 'FILTER' | 'ARTICLE' | 'CONTENT' | 'CART' | 'CMS' | 'DICTIONARY' | 'ITEM' | 'NOTIFICATION' | 'ORDER' | 'PAYMENT' | 'REVIEW' | 'USER' | 'WEB' | 'WEB_API' | 'FISCALIZATION' | 'LOGISTICS' | 'RSHB_INTEGRATION' | 'MAKER_CHECKER' | 'UNDEFINED' | 'EVENT_LOG' | 'REPORT' | 'EXTERNAL_FEED' | 'SEARCH' | 'EASWAAQ' | 'INTEGRATION' | 'CHAT';
    export const ServiceEnum = {
        FILTER: 'FILTER' as ServiceEnum,
        ARTICLE: 'ARTICLE' as ServiceEnum,
        CONTENT: 'CONTENT' as ServiceEnum,
        CART: 'CART' as ServiceEnum,
        CMS: 'CMS' as ServiceEnum,
        DICTIONARY: 'DICTIONARY' as ServiceEnum,
        ITEM: 'ITEM' as ServiceEnum,
        NOTIFICATION: 'NOTIFICATION' as ServiceEnum,
        ORDER: 'ORDER' as ServiceEnum,
        PAYMENT: 'PAYMENT' as ServiceEnum,
        REVIEW: 'REVIEW' as ServiceEnum,
        USER: 'USER' as ServiceEnum,
        WEB: 'WEB' as ServiceEnum,
        WEBAPI: 'WEB_API' as ServiceEnum,
        FISCALIZATION: 'FISCALIZATION' as ServiceEnum,
        LOGISTICS: 'LOGISTICS' as ServiceEnum,
        RSHBINTEGRATION: 'RSHB_INTEGRATION' as ServiceEnum,
        MAKERCHECKER: 'MAKER_CHECKER' as ServiceEnum,
        UNDEFINED: 'UNDEFINED' as ServiceEnum,
        EVENTLOG: 'EVENT_LOG' as ServiceEnum,
        REPORT: 'REPORT' as ServiceEnum,
        EXTERNALFEED: 'EXTERNAL_FEED' as ServiceEnum,
        SEARCH: 'SEARCH' as ServiceEnum,
        EASWAAQ: 'EASWAAQ' as ServiceEnum,
        INTEGRATION: 'INTEGRATION' as ServiceEnum,
        CHAT: 'CHAT' as ServiceEnum
    };
}