/**
 * Chat service API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ChatMemberShared { 
    id?: number;
    profileId?: number;
    fullName?: string;
    profileType?: ChatMemberShared.ProfileTypeEnum;
    kicked?: boolean;
    chatId?: number;
}
export namespace ChatMemberShared {
    export type ProfileTypeEnum = 'COMMON_BUYER' | 'COMMON_SELLER' | 'LEGAL_BUYER' | 'LEGAL_SELLER' | 'OPERATOR' | 'COMMON_AGENT' | 'LEGAL_AGENT' | 'UNKNOWN' | 'MODERATOR' | 'TECHNICAL_USER' | 'COURIER';
    export const ProfileTypeEnum = {
        COMMONBUYER: 'COMMON_BUYER' as ProfileTypeEnum,
        COMMONSELLER: 'COMMON_SELLER' as ProfileTypeEnum,
        LEGALBUYER: 'LEGAL_BUYER' as ProfileTypeEnum,
        LEGALSELLER: 'LEGAL_SELLER' as ProfileTypeEnum,
        OPERATOR: 'OPERATOR' as ProfileTypeEnum,
        COMMONAGENT: 'COMMON_AGENT' as ProfileTypeEnum,
        LEGALAGENT: 'LEGAL_AGENT' as ProfileTypeEnum,
        UNKNOWN: 'UNKNOWN' as ProfileTypeEnum,
        MODERATOR: 'MODERATOR' as ProfileTypeEnum,
        TECHNICALUSER: 'TECHNICAL_USER' as ProfileTypeEnum,
        COURIER: 'COURIER' as ProfileTypeEnum
    };
}