/**
 * Chat service API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ChatCreateRequest { 
    title: string;
    type: ChatCreateRequest.TypeEnum;
    entityId?: number;
    creatorProfileId?: number;
    creatorProfileType?: ChatCreateRequest.CreatorProfileTypeEnum;
    opponentProfileId?: number;
    opponentIsLegal?: boolean;
}
export namespace ChatCreateRequest {
    export type TypeEnum = 'SUPPORT' | 'ITEM' | 'ORDER' | 'RFQ' | 'FACTORING' | 'REVERSE_FACTORING' | 'POSTPONEMENT' | 'CREDIT';
    export const TypeEnum = {
        SUPPORT: 'SUPPORT' as TypeEnum,
        ITEM: 'ITEM' as TypeEnum,
        ORDER: 'ORDER' as TypeEnum,
        RFQ: 'RFQ' as TypeEnum,
        FACTORING: 'FACTORING' as TypeEnum,
        REVERSEFACTORING: 'REVERSE_FACTORING' as TypeEnum,
        POSTPONEMENT: 'POSTPONEMENT' as TypeEnum,
        CREDIT: 'CREDIT' as TypeEnum
    };
    export type CreatorProfileTypeEnum = 'COMMON_BUYER' | 'COMMON_SELLER' | 'LEGAL_BUYER' | 'LEGAL_SELLER' | 'OPERATOR' | 'COMMON_AGENT' | 'LEGAL_AGENT' | 'UNKNOWN' | 'MODERATOR' | 'TECHNICAL_USER' | 'COURIER';
    export const CreatorProfileTypeEnum = {
        COMMONBUYER: 'COMMON_BUYER' as CreatorProfileTypeEnum,
        COMMONSELLER: 'COMMON_SELLER' as CreatorProfileTypeEnum,
        LEGALBUYER: 'LEGAL_BUYER' as CreatorProfileTypeEnum,
        LEGALSELLER: 'LEGAL_SELLER' as CreatorProfileTypeEnum,
        OPERATOR: 'OPERATOR' as CreatorProfileTypeEnum,
        COMMONAGENT: 'COMMON_AGENT' as CreatorProfileTypeEnum,
        LEGALAGENT: 'LEGAL_AGENT' as CreatorProfileTypeEnum,
        UNKNOWN: 'UNKNOWN' as CreatorProfileTypeEnum,
        MODERATOR: 'MODERATOR' as CreatorProfileTypeEnum,
        TECHNICALUSER: 'TECHNICAL_USER' as CreatorProfileTypeEnum,
        COURIER: 'COURIER' as CreatorProfileTypeEnum
    };
}