/**
 * Chat service API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MessageShared } from './messageShared';

export interface ChatShared { 
    id?: number;
    title?: string;
    type?: ChatShared.TypeEnum;
    messages?: Array<MessageShared>;
    unreadMessages?: Array<MessageShared>;
}
export namespace ChatShared {
    export type TypeEnum = 'SUPPORT' | 'ITEM' | 'ORDER' | 'RFQ' | 'FACTORING' | 'REVERSE_FACTORING' | 'POSTPONEMENT' | 'CREDIT';
    export const TypeEnum = {
        SUPPORT: 'SUPPORT' as TypeEnum,
        ITEM: 'ITEM' as TypeEnum,
        ORDER: 'ORDER' as TypeEnum,
        RFQ: 'RFQ' as TypeEnum,
        FACTORING: 'FACTORING' as TypeEnum,
        REVERSEFACTORING: 'REVERSE_FACTORING' as TypeEnum,
        POSTPONEMENT: 'POSTPONEMENT' as TypeEnum,
        CREDIT: 'CREDIT' as TypeEnum
    };
}