/**
 * Chat service API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChatMemberShared } from './chatMemberShared';
import { MessageShared } from './messageShared';

export interface ChatInfoByUserShared { 
    unreadMessages?: number;
    chatTitle?: string;
    chatType?: ChatInfoByUserShared.ChatTypeEnum;
    lastMessage?: MessageShared;
    chatMembers?: Array<ChatMemberShared>;
}
export namespace ChatInfoByUserShared {
    export type ChatTypeEnum = 'SUPPORT' | 'ITEM' | 'ORDER' | 'RFQ' | 'FACTORING' | 'REVERSE_FACTORING' | 'POSTPONEMENT' | 'CREDIT';
    export const ChatTypeEnum = {
        SUPPORT: 'SUPPORT' as ChatTypeEnum,
        ITEM: 'ITEM' as ChatTypeEnum,
        ORDER: 'ORDER' as ChatTypeEnum,
        RFQ: 'RFQ' as ChatTypeEnum,
        FACTORING: 'FACTORING' as ChatTypeEnum,
        REVERSEFACTORING: 'REVERSE_FACTORING' as ChatTypeEnum,
        POSTPONEMENT: 'POSTPONEMENT' as ChatTypeEnum,
        CREDIT: 'CREDIT' as ChatTypeEnum
    };
}