/**
 * Chat service API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChatMemberShared } from './chatMemberShared';
import { FileAttachment } from './fileAttachment';

export interface MessageShared { 
    id?: number;
    creator?: ChatMemberShared;
    messageText?: string;
    guid?: string;
    attachments?: Array<FileAttachment>;
    createdAt?: Date;
    updatedAt?: Date;
}