/**
 * Chat service API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChatPaginationShared } from './chatPaginationShared';

export interface PageChatPaginationShared { 
    data?: Array<ChatPaginationShared>;
    totalCount?: number;
    currentPage?: number;
}